name: Verify if PDF Presenter builds

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - name: Update the repos
              run: sudo apt update
            - name: Install dependencies
              run: sudo apt install -y libgtk-4-dev libpoppler-dev libpoppler-glib-dev
            - name: Build Pdf-Presenter
              run: ./build.sh
